### ISSUE TITLE
Kick after one message on Tchat

### ISSUE THREAD

**Issue by Batsave** [Majhrs16/ChatTranslator#2]
**FR Version** 

J'ai rencontré un problème avec le plugin que j'utilise sur mon serveur Mohist 1.20.1. Bien que de nombreux problèmes aient été résolus dans cette version V2.0, un nouveau problème majeur est apparu. Peu importe la valeur que je fixe pour "max spam par tick", les utilisateurs se font expulser pour spam après un seul message. Avez-vous une solution pour résoudre ce problème?

**EN Version** 

I encountered a problem with the plugin I use on my Mohist 1.20.1 server. Although many issues have been resolved in this version 2.0, a new major problem has appeared. No matter what value I set for "max spam per tick", users get kicked out for spam after a single message. Do you have a solution to resolve this issue?

**ES Version**

Encontré un problema con el plugin que uso en mi servidor Mohist 1.20.1. Aunque se han resuelto muchos problemas en esta versión 2.0, ha aparecido un nuevo problema importante. No importa qué valor establezca para "max spam por tick", los usuarios son expulsados por spam después de un solo mensaje. ¿Tienes una solución para resolver este problema?

Thanks in advance ! 

Batsave

**Comment by Majhrs16** [comment]
<details>
  <summary>Español</summary>

Es raro que aun hables de la configuración antigua `max-spam-per-tick`.

En el actual [config.yml](https://github.com/Majhrs16/ChatTranslator/blob/main/src/main/resources/config.yml), esta la sección `spam`:
```yaml
spam:
  max-ticks: 60
  max-messages: 7
```

Quizás haya ocurrido algún error en la actualización del mismo..

---

Podrías decirme:
- Que versión usabas antes de la `v2.0`?
- Cual es la estructura general de tu `config.yml`?
- Tienes activada la actualización de la configuración? 
</details>

---

<details>
  <summary>English</summary>

It’s strange that you’re still talking about the old `max-spam-per-tick` configuration.

In the current config.yml, there’s a `spam` section:

```yaml
spam:
  max-ticks: 60
  max-messages: 7
```

Perhaps there was an error during the update.

---

Could you tell me:
- Is configuration updating enabled?
- Which version were you using before `v2.0`?
- What is the general structure of your `config.yml`?
</details>

**Comment by Batsave** [comment]
in fact there was a problem with the configuration file, I was able to reinstall and the problem went away (probably leftovers from v1) 

thanks
